// Datos mock para desarrollo
export const USUARIOS_MOCK = [
  {
    id: '1',
    nombre: 'Juan Pérez',
    email: 'juan@ejemplo.com',
    password: '123456',
    telefono: '666777888',
    vivienda: 'Casa 42',
    esAdmin: false,
    estadoAprobacion: 'aprobado', // 'pendiente' | 'aprobado' | 'rechazado'
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    nombre: 'María García',
    email: 'maria@ejemplo.com',
    password: '123456',
    telefono: '655444333',
    vivienda: 'Piso 3-A',
    esAdmin: true,
    estadoAprobacion: 'aprobado',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '3',
    nombre: 'Pedro Martínez',
    email: 'pedro@ejemplo.com',
    password: '123456',
    telefono: '644555666',
    vivienda: 'Casa 15',
    esAdmin: false,
    estadoAprobacion: 'pendiente',
    createdAt: new Date('2025-12-22'),
  },
];

export const RESERVAS_MOCK = [
  {
    id: '1',
    pistaId: '1',
    pistaNombre: 'Pista de Pádel',
    usuarioId: '1',
    usuarioNombre: 'Juan Pérez',
    fecha: '2025-12-23',
    horaInicio: '10:00',
    horaFin: '11:30',
    estado: 'confirmada',
    jugadores: ['Pedro López', 'Ana Martín'],
    createdAt: new Date('2025-12-20'),
    updatedAt: new Date('2025-12-20'),
  },
  {
    id: '2',
    pistaId: '1',
    pistaNombre: 'Pista de Pádel',
    usuarioId: '2',
    usuarioNombre: 'María García',
    fecha: '2025-12-18',
    horaInicio: '09:00',
    horaFin: '10:30',
    estado: 'completada',
    jugadores: ['Laura Sánchez', 'Marta Díaz'],
    createdAt: new Date('2025-12-15'),
    updatedAt: new Date('2025-12-18'),
  },
];
