import { StyleSheet } from 'react-native';
import { colors } from '../../../constants/colors';

export const styles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.6)', justifyContent: 'center', alignItems: 'center', padding: 20, zIndex: 9999, elevation: 9999 },
  content: { backgroundColor: colors.surface, borderRadius: 16, padding: 24, width: '100%', maxWidth: 400, maxHeight: '80%', zIndex: 10000, elevation: 10000 },
  title: { fontSize: 20, fontWeight: '600', color: colors.text, marginBottom: 16, textAlign: 'center' },
  typeButtons: { flexDirection: 'row', gap: 8, marginBottom: 16 },
  typeButton: { flex: 1, paddingVertical: 10, borderRadius: 8, borderWidth: 1, borderColor: colors.border, alignItems: 'center' },
  typeButtonActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  typeButtonText: { fontSize: 14, color: colors.text },
  typeButtonTextActive: { color: '#fff', fontWeight: '600' },
  searchContainer: { flex: 1 },
  searchInput: { backgroundColor: colors.background, borderRadius: 8, padding: 12, fontSize: 14, color: colors.text, borderWidth: 1, borderColor: colors.border, marginBottom: 12 },
  usersList: { maxHeight: 300 },
  loading: { padding: 40, alignItems: 'center' },
  noResults: { color: colors.textSecondary, fontSize: 14, textAlign: 'center', padding: 20 },
  userOption: { flexDirection: 'row', alignItems: 'center', padding: 12, backgroundColor: colors.surface, borderRadius: 8, marginBottom: 8, borderWidth: 1, borderColor: colors.border },
  userOptionDisabled: { opacity: 0.5 },
  userAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.secondary, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  userAvatarImage: { width: 40, height: 40, borderRadius: 20 },
  userAvatarText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  userInfo: { flex: 1 },
  userName: { fontSize: 15, fontWeight: '500', color: colors.text },
  userNameDisabled: { color: colors.textSecondary },
  userApartment: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
  externalContainer: { flex: 1 },
  label: { fontSize: 14, fontWeight: '600', color: colors.textSecondary, marginBottom: 8, marginTop: 12 },
  externalInput: { backgroundColor: colors.background, borderRadius: 8, padding: 12, fontSize: 14, color: colors.text, borderWidth: 1, borderColor: colors.border },
  levelsContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  levelOption: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16, borderWidth: 1, borderColor: colors.border },
  levelOptionSelected: { backgroundColor: colors.primary, borderColor: colors.primary },
  levelOptionText: { fontSize: 13, color: colors.text },
  levelOptionTextSelected: { color: '#fff', fontWeight: '500' },
  addExternalButton: { backgroundColor: colors.primary, borderRadius: 8, padding: 14, alignItems: 'center', marginTop: 20 },
  addExternalButtonText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  closeButton: { marginTop: 16, padding: 12, alignItems: 'center' },
  closeButtonText: { color: colors.textSecondary, fontSize: 15, fontWeight: '500' },
});
