import { StyleSheet } from 'react-native';
import { colors } from '../../../constants/colors';

export const styles = StyleSheet.create({
  card: { backgroundColor: colors.surface, borderRadius: 12, padding: 16, marginBottom: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 2, borderWidth: 2, borderColor: 'transparent' },
  cardComplete: { borderColor: colors.guaranteedReservation },
  cardClass: { backgroundColor: colors.classBackground, borderColor: colors.classColor },
  cardClassComplete: { borderColor: colors.classColor },
  classBadgeContainer: { position: 'absolute', top: 0, right: 0, backgroundColor: colors.classColor, paddingHorizontal: 10, paddingVertical: 4, borderTopRightRadius: 10, borderBottomLeftRadius: 10 },
  classBadgeText: { color: '#fff', fontSize: 10, fontWeight: '700', letterSpacing: 0.5 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  creatorName: { fontSize: 16, fontWeight: '600', color: colors.text },
  creatorApartment: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
  badge: { backgroundColor: colors.primary + '20', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  badgeComplete: { backgroundColor: colors.guaranteedReservation + '20' },
  badgeText: { fontSize: 13, fontWeight: '600', color: colors.primary },
  badgeTextComplete: { color: colors.guaranteedReservation },
  badgeClass: { backgroundColor: colors.classColor + '20' },
  badgeClassComplete: { backgroundColor: colors.classColor + '30' },
  badgeTextClass: { color: colors.classColor },
  classInfoContainer: { backgroundColor: colors.surface, borderRadius: 8, padding: 10, marginBottom: 10, borderWidth: 1, borderColor: colors.classColor + '30' },
  classInfoText: { fontSize: 13, color: colors.text, marginBottom: 4 },
  classPrices: { flexDirection: 'row', gap: 12, marginTop: 4 },
  classPrice: { fontSize: 14, fontWeight: '600', color: colors.classColor },
  dateContainer: { marginBottom: 8 },
  date: { fontSize: 14, color: colors.text, fontWeight: '500' },
  openDate: { fontSize: 14, color: colors.accent, fontStyle: 'italic' },
  level: { fontSize: 13, color: colors.textSecondary, marginBottom: 8 },
  message: { fontSize: 14, color: colors.text, fontStyle: 'italic', marginBottom: 12, backgroundColor: colors.background, padding: 10, borderRadius: 8 },
  actions: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 8, marginTop: 4 },
  primaryButton: { backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },
  primaryButtonText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  editButton: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.primary, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },
  editButtonText: { color: colors.primary, fontWeight: '600', fontSize: 14 },
  editButtonClass: { borderColor: colors.classColor },
  editButtonTextClass: { color: colors.classColor },
  primaryButtonClass: { backgroundColor: colors.classColor },
  closeClassButton: { backgroundColor: colors.classColor, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },
  closeClassButtonText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  cancelButton: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.error, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },
  cancelButtonText: { color: colors.error, fontWeight: '600', fontSize: 14 },
  secondaryButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6, borderWidth: 1, borderColor: colors.textSecondary },
  secondaryButtonText: { fontSize: 13, color: colors.textSecondary },
  pendingRequest: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  pendingRequestText: { fontSize: 14, color: colors.accent, fontStyle: 'italic' },
});
